---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  interval: 10m
