---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - flux-operator.yaml
  - ingress-nginx.yaml
  - metrics-server.yaml
