---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      interval: 1m0s
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
      version: 61.x
  interval: 1m0s
  values:
    grafana:
      additionalDataSources:
        - name: Loki
          access: proxy
          isDefault: false
          jsonData:
            httpHeaderName1: X-Scope-OrgID
          secureJsonData:
            httpHeaderValue1: 1
          orgId: 1
          type: loki
          url: http://loki-gateway.monitoring.svc.cluster.local/
