---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metrics-server
      interval: 1m0s
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: 3.12.1
  interval: 1m0s
  values:
    args:
      - --kubelet-insecure-tls
