---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-nats
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 60m
  path: ./apps/nats/base
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
  wait: true
