---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: infrastructure-configs
  interval: 60m
  path: ./monitoring/base
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
  wait: true
