---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 0.x
  interval: 10m
  values:
    alloy:
      configMap:
        content: |-
          discovery.kubernetes "pods" {
            role = "pod"
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [loki.write.default.receiver]
          }

          loki.write "default" {
            endpoint {
              url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
            }
          }

          prometheus.scrape "pods" {
            targets = discovery.kubernetes.pods.targets
            forward_to = [prometheus.remote_write.default.receiver]
          }

          prometheus.remote_write "default" {
            endpoint {
              url = "http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push"
            }
          }
