---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 8.x
  driftDetection:
    mode: enabled
  interval: 10m
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            uid: loki
            editable: false
            type: loki
            url: http://loki-gateway.monitoring.svc.cluster.local
          - name: Mimir
            uid: mimir
            editable: false
            isDefault: true
            type: prometheus
            url: http://mimir-gateway.monitoring.svc.cluster.local/prometheus
          - name: Tempo
            uid: tempo
            editable: false
            isDefault: false
            jsonData:
              tracesToLogsV2:
                datasourceUid: loki
              lokiSearch:
                datasourceUid: loki
              tracesToMetrics:
                datasourceUid: mimir
              serviceMap:
                datasourceUid: mimir
            type: tempo
            url: http://tempo-gateway.monitoring.svc.cluster.local
    persistence:
      enabled: true
    replicas: 2
