---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 8.x
  interval: 10m
  values:
    persistence:
      enabled: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: http://loki-gateway.monitoring.svc.cluster.local
          - name: Mimir
            type: prometheus
            url: http://mimir-gateway.monitoring.svc.cluster.local/prometheus
            isDefault: true
