---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 1.x
  driftDetection:
    mode: enabled
  interval: 10m
  timeout: 3m
  values:
    cluster:
      name: ${CLUSTER_NAME}
    externalServices:
      prometheus:
        host: http://mimir-gateway.monitoring.svc.cluster.local
        queryEndpoint: /prometheus/api/v1/query
        writeEndpoint: /api/v1/push
        authMode: none
      loki:
        host: http://loki-gateway.monitoring.svc.cluster.local
        authMode: none
      tempo:
        host: http://tempo-gateway.monitoring.svc.cluster.local
        authMode: none
    opencost:
      opencost:
        prometheus:
          existingSecretName: null
          username_key: null
          password_key: null
          external:
            url: http://mimir-gateway.monitoring.svc.cluster.local/prometheus
