---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 24h
  url: https://kubernetes.github.io/kube-state-metrics
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
      version: 2.x
  driftDetection:
    mode: enabled
  interval: 10m
