---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - kube-state-metrics.yaml
  - loki.yaml
  - mimir.yaml
  - minio.yaml
  - otel-collector.yaml
  - tempo.yaml
