---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy.yaml
  - grafana.yaml
  - loki.yaml
  - mimir.yaml
  - minio.yaml
  - namespace.yaml
  - repository.yaml
  - tempo.yaml
