---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 6.x
  interval: 10m
  values:
    loki:
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: '2024-04-01'
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      auth_enabled: false
    gateway:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: gateway
                  app.kubernetes.io/name: loki
              topologyKey: kubernetes.io/hostname
    write:
      replicas: 1
    read:
      replicas: 1
    backend:
      replicas: 1
    resultsCache:
      enabled: false
    chunksCache:
      enabled: false
    minio:
      enabled: true
    test:
      enabled: false
    lokiCanary:
      enabled: false
