---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  chart:
    spec:
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 5.x
  interval: 10m
  values:
    ingester:
      replicas: 2
      zoneAwareReplication:
        enabled: false
    querier:
      replicas: 1
    query_scheduler:
      replicas: 1
    store_gateway:
      zoneAwareReplication:
        enabled: false
