---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  chart:
    spec:
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 5.x
  dependsOn:
    - name: minio
  interval: 10m
  values:
    # Distributed configuration
    ingester:
      replicas: 1
      zoneAwareReplication:
        enabled: false
    ruler_querier:
      replicas: 1
    ruler_query_scheduler:
      replicas: 1
    querier:
      replicas: 1
    query_scheduler:
      replicas: 1
    store_gateway:
      replicas: 1
      zoneAwareReplication:
        enabled: false
    # Extra configuration
    minio:
      enabled: false
    rollout_operator:
      enabled: false
    # Gateway configuration
    gateway:
      enabledNonEnterprise: true
    nginx:
      enabled: false
    # Mimir configuration
    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              access_key_id: mimir
              secret_access_key: mimir123!
              endpoint: minio.monitoring.svc.cluster.local:9000
              insecure: true
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        blocks_storage:
          s3:
            bucket_name: mimir-blocks
        ruler_storage:
          s3:
            bucket_name: mimir-ruler
