---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  chart:
    spec:
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 5.x
  interval: 10m
  values:
    gateway:
      enabledNonEnterprise: true
    nginx:
      enabled: false
