---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: monitoring
spec:
  interval: 24h
  url: https://charts.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: monitoring
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
      version: 5.x
  interval: 10m
  values:
    mode: standalone
    persistence:
      size: 10Gi
    resources:
      requests:
        memory: 128Mi
