---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: monitoring
spec:
  interval: 24h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  chart:
    spec:
      chart: opentelemetry-kube-stack
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.x
  driftDetection:
    mode: enabled
  interval: 10m
  values:
    defaultCRConfig:
      config:
        exporters:
          otlphttp/logs:
            endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
            tls:
              insecure: true
          prometheusremotewrite:
            endpoint: http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push
            tls:
              insecure: true
        service:
          pipelines:
            logs:
              exporters:
                - otlphttp/logs
            metrics:
              exporters:
                - prometheusremotewrite
      presets:
        kubernetesAttributes:
          extractAllPodLabels: true
    opentelemetry-operator:
      manager:
        collectorImage:
          repository: otel/opentelemetry-collector-contrib
