---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: monitoring
spec:
  interval: 24h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector-daemon
  namespace: monitoring
spec:
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.x
  driftDetection:
    mode: enabled
  interval: 10m
  values:
    config:
      exporters:
        otlphttp/logs:
          endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
          tls:
            insecure: true
        prometheusremotewrite:
          endpoint: http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push
          tls:
            insecure: true
      receivers:
        jaeger: null
        kubeletstats:
          insecure_skip_verify: true
        zipkin: null
      service:
        pipelines:
          logs:
            exporters:
              - otlphttp/logs
          metrics:
            exporters:
              - prometheusremotewrite
          traces:
            receivers:
              - otlp
    fullnameOverride: otel-collector-daemon
    image:
      repository: otel/opentelemetry-collector-contrib
    mode: daemonset
    ports:
      jaeger-compact:
        enabled: false
      jaeger-grpc:
        enabled: false
      jaeger-thrift:
        enabled: false
      zipkin:
        enabled: false
    presets:
      hostMetrics:
        enabled: true
      kubeletMetrics:
        enabled: true
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
      logsCollection:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector-cluster
  namespace: monitoring
spec:
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.x
  driftDetection:
    mode: enabled
  interval: 10m
  values:
    config:
      exporters:
        otlphttp/logs:
          endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
          tls:
            insecure: true
        prometheusremotewrite:
          endpoint: http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push
          tls:
            insecure: true
      receivers:
        jaeger: null
        kubeletstats:
          insecure_skip_verify: true
        zipkin: null
      service:
        pipelines:
          logs:
            exporters:
              - otlphttp/logs
          metrics:
            exporters:
              - prometheusremotewrite
          traces:
            receivers:
              - otlp
    fullnameOverride: otel-collector-cluster
    image:
      repository: otel/opentelemetry-collector-contrib
    mode: deployment
    ports:
      jaeger-compact:
        enabled: false
      jaeger-grpc:
        enabled: false
      jaeger-thrift:
        enabled: false
      zipkin:
        enabled: false
    presets:
      clusterMetrics:
        enabled: true
      kubernetesEvents:
        enabled: false
        enabled: true
